WIDTH = 800
HEIGHT = 600
FPS = 60
BACKGROUND_COLOR = (255, 255, 255)

APP_NAME = "Drone Delivery"
DEFAULT_PX_PER_METER = 100

KEY_W = "KEY_W"
KEY_S = "KEY_S"
KEY_A = "KEY_A"
KEY_D = "KEY_D"
KEY_UP = "KEY_UP"
KEY_DOWN = "KEY_DOWN"
KEY_LEFT = "KEY_LEFT"
KEY_RIGHT = "KEY_RIGHT"


